services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_DATABASE: meubanco        
      MYSQL_USER: usuario       
      MYSQL_PASSWORD: senha123           
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  springboot-app:
    build: .
    container_name: spring-data-jpa
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/meubanco
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha123
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MariaDBDialect
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
